### ISSUE TITLE
Error compiling with webpack

### ISSUE THREAD

**Issue by prizzio** [formio/angular-formio#159]
Hello,

This isn't a error of formio, but I hope that somebody help me with this issue.

When I launch "ng serve" ....

```
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-02-19T17:09:44.747Z
Hash: 37551eb9884f298f9dc2
Time: 43225ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.44 MB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 599 kB [initial] [rendered]
chunk {scripts} scripts.bundle.js (scripts) 1.23 MB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 2.84 MB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 19.5 MB [initial] [rendered]

ERROR in multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
Module not found: Error: Can't resolve 'webpack-dev-server/client?http://0.0.0.0:0' in 'C:\Desarrollo\vsn_cms_formio\client'
ERROR in Error: Metadata version mismatch for module C:/Desarrollo/vsn_cms_formio/client/node_modules/angular-formio/index.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/Desarrollo/vsn_cms_formio/client/src/app/app.module.ts, resolving symbol AppModule in C:/Desarrollo/vsn_cms_formio/client/src/app/app.module.ts
    at syntaxError (C:\Desarrollo\vsn_cms_formio\client\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (C:\Desarrollo\vsn_cms_formio\client\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
    at StaticReflector.simplify (C:\Desarrollo\vsn_cms_formio\client\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
    at StaticReflector.annotations (C:\Desarrollo\vsn_cms_formio\client\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (C:\Desarrollo\vsn_cms_formio\client\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (C:\Desarrollo\vsn_cms_formio\client\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (C:\Desarrollo\vsn_cms_formio\client\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Desarrollo\vsn_cms_formio\client\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (C:\Desarrollo\vsn_cms_formio\client\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\plugin.js:240:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\Desarrollo\vsn_cms_formio\client\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\plugin.js:493:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I am using in package.json :

`"angular-formio": "^1.16.0",`

And in app.module.ts:

```
import { FormioModule } from 'angular-formio';
..
imports:     
   FormioModule,
..
```

PD: With old version of formio 1.12 works
PD2: I tried with version 1.15 too and doesn't works

Thank you

**Comment by travist** [comment]
Yep, this happens because the build routine creates a ```index.metadata.json``` file based on the version of Angular when I compiled it. As it turns out, I was on Angular 5 when compiling the library and it added the version 4 for that (I know it is confusing but Angular 5 = version 4). You must be on Angular 4 so therefore you are on version 3, and that is why it is complaining. Let me do some digging and figure out how to get the ```index.metadata.json``` not care about your version.

**Comment by prizzio** [comment]
Thank you travist.  I will also investigate about this

**Comment by prizzio** [comment]
Hi,

Finally, after reading some about this I updated the @angular versions on package.json from 4.0.0 to 5.2.5

```
"@angular/animations": "^5.2.5",
"@angular/cdk": "^5.2.1",
"@angular/common": "^5.2.5",
"@angular/compiler": "^5.2.5",
"@angular/core": "^5.2.5",
"@angular/forms": "^5.2.5",
"@angular/http": "^5.2.5",
"@angular/material": "^5.2.1",
"@angular/platform-browser": "^5.2.5",
"@angular/platform-browser-dynamic": "^5.2.5",
"@angular/router": "^5.2.5"
```

I have another doubt but I will open another ticket.

Thank you
